version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: hamza
      POSTGRES_PASSWORD: pass
    volumes:
      - ./data:/var/lib/postgresql/data2
    ports:
      - 5434:5434

  web:
    build: .
    ports:
      - 5000:80
    depends_on:
      - db